project:
  type: website
  output-dir: docs

website:
  title: "geryan.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    

editor: visual

