project:
  type: website
  output-dir: docs

website:
  title: "Gerry Ryan"
  body-header: |
    ![](/images/dsc_0594-1680_wide_bw.png){.site-banner fig-alt="Black and white photograph of a bicycle partly submerged in water"}
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - software.qmd
  page-footer:
    center: |
      In the spirit of reconciliation I acknowledge the Traditional Custodians 
      of Country throughout Australia and their connections to land, waters, and
      community. I pay my respects to their Elders past and present and extend 
      that respect to all Aboriginal and Torres Strait Islander peoples.



format:
  html:
    theme: litera
    css: styles.css
    toc: true
    

editor: visual

