project:
  type: website
  output-dir: docs

website:
  title: "geryan.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
  page-footer:
    center: |
      In the spirit of reconciliation I acknowledge the Traditional Custodians of Country throughout Australia and their connections to land, waters, and community. I pay our respect to their Elders past and present and extend that respect to all Aboriginal and Torres Strait Islander peoples.



format:
  html:
    theme: litera
    css: styles.css
    toc: true
    

editor: visual

