---
title: "Publications"
---

*Most articles are free to read, but contact me for pdfs:*

[gerry.ryan\@thekids.org.au](mailto:gerry.ryan@thekids.org.au){.email}

<!-- Leap ahead to:\ -->

<!--   - [Pre-prints](#pre-prints)\ -->

<!--   - [Peer-reviewed articles](#peer-reviewed-articles)\ -->

<!--   - [Grey Literature](#grey-literature)\ -->

<!--   - [Data](#data)\ -->

<!--   - [Archived Code](#archived-code)\ -->

<!--   - [Published Pre-prints](#published-pre-prints)\ -->

## Pre-prints

Conway, E., Walker, C., Lydeamore, M., Golding, N., **Ryan, G.**, Mavec, D., Oates J., Kabashima, G., Price, D.J., Shearer, F, Cromer, D., Davenport, M.P., McCaw, J., Eriksson, E.M., Hodgkin, P.D., Wu, L., Le, T.P, Baker, C.M., Mueller, I., and McVernon, J. (2024). [Optimal timing of booster doses in a highly vaccinated population with minimal natural exposure to COVID-19](https://doi.org/10.1101/2024.05.14.24307386){target="_blank"}. **medRxiv** 2024.05.14.24307386

Le, T.P., Conway, E., Akpan, E., Abell, I., Abraham, P., Baker, C.M., Campbell, P.T., Cromer, D., Lydeamore, M.J., McDonough, Y., Mueller, I., **Ryan, G.**, Walker, C., Wang, Y., Carvalho, N., and McVernon, J. (2023). [Cost-effective boosting allocations in the post-Omicron era of COVID-19 management](https://doi.org/10.1101/2023.11.14.23298536){target="_blank"}. **medRxiv** 2023.11.14.23298536.

## Peer-reviewed articles

24.  Eales, O., Teo, M., Price, D.J., Hao, T., **Ryan, G.E.**, Senior, K.L., Carlson, S., Dalton, C., Dawson, P., Golding, N., McCaw, J.M., and Shearer, F.M. (2024). [Temporal trends in test-seeking behaviour during the COVID-19 pandemic](https://doi.org/10.1080/29937574.2025.2521858){target="_blank"}. **Mathematics in Medical and Life Sciences** DOI 10.1080/29937574.2025.2521858

23. **Ryan, G.E.**, Tierney, N., Golding, N., and Weiss, D.J (2025). [traveltime: an R package to calculate travel time across a landscape from user-specified locations](https://doi.org/10.12688/gatesopenres.16356.1){target="_blank"}. **Gates Open Research** 9:50

22. Hao, T., **Ryan, G.E.**, Lydeamore, M., Cromer, D., Wood, J, McVernon, J, McCaw, J, Shearer, F.M., and Golding N. (2025). [Predicting immune protection against outcomes of infectious disease from population-level effectiveness data with application to COVID-19](https://doi.org/10.1016/j.vaccine.2025.126987){target="_blank"}. **Vaccine** 55: 126987

21. **Ryan, G.E.**, Nicholson, E., Baker, C.M., and McCarthy, M. A. (2024). [The costs and benefits of publicising species discoveries](https://doi.org/10.1111/conl.13044){target="_blank"}. **Conservation Letters** 17(5): e13044

20. Shearer, F.M, Edwards, L., Kirk, M., Eales, O., Golding, N., Hassall, J., Liu, B., Lydeamore, M., Miller, C., Moss, R., Price, D.J., **Ryan, G.E**, Sullivan, S., Tobin, R., Ward, K., Kaldor, K., Cheng, A.C., Wood, J., and McCaw, J.M. (2024). [Opportunities to strengthen respiratory virus surveillance systems in Australia: lessons learned from the COVID-19 response](https://doi.org/10.33321/cdi.2024.48.47){target="blank"}. **Communicable Diseases Intelligence** 2024 (48) https://doi.org/10.33321/cdi.2024.48.47

19. Shearer, F.M., McCaw, J.M., **Ryan, G.E.**, Hao, T., Tierney, N., Lydeamore, M., Ellis, S., Ward, K., Wood, J., McVernon, J. and Golding, N., (2024). [Estimating the impact of test-trace-isolate-quarantine systems on SARS-CoV-2 transmission in Australia](https://doi.org/10.1016/j.epidem.2024.100764){target="_blank"}. **Epidemics** 47(2024): 100764

18. **Ryan, G.E.**, Shearer, F.M., McCaw, J.M., McVernon, J. and Golding, N., (2024). [Estimating measures to reduce the transmission of SARS-CoV-2 in Australia to guide a ‘National Plan’ to reopening](https://doi.org/10.1016/j.epidem.2024.100763){target="_blank"}. **Epidemics** 47(2024): 100763

17. Zachreson, C., Tobin, R., Szanyi, J., Walker, C., Cromer, D., Shearer, F.M., Conway, E., **Ryan, G.**, Cheng, A., McCaw, J.M. and Geard, N., (2023). [Individual variation in vaccine immune response can produce bimodal distributions of protection](https://doi.org/10.1016/j.vaccine.2023.09.025){target="_blank"}. **Vaccine** 41(45): 6630--6636.

16. Conway, E., Walker, C.R., Baker, C., Lydeamore, M.J., **Ryan, G.E.**, Campbell, T., Miller, J.C., Rebuli, N., Yeung, M., Kabashima, G., Geard, N., Wood, J., McCaw, J.M., McVernon, J., Golding, N., Price, D.J, & Shearer, F.M. (2023). [COVID-19 vaccine coverage targets to inform reopening plans in a low incidence setting](https://doi.org/10.1098/rspb.2023.1437){target="_blank"}. **Proceedings of the Royal Society B**, 290(2005): 20231437.

15. Golding, N., Price, D.J., **Ryan, G.**, McVernon, J., McCaw, J.M. and Shearer, F.M., (2023). [A modelling approach to estimate the transmissibility of SARS-CoV-2 during periods of high, low, and zero case incidence](https://doi.org/10.7554/eLife.78089){target="_blank"}. **eLife**, 12: e78089.

14. Borzée, A., McNeely, J., Magellan, K., Miller, J.R., Porter, L., Dutta, T., Kadinjappalli, K.P., Sharma, S., Shahabuddin, G., Aprilinayati, F., **Ryan, G.E** and others (2020). [COVID-19 Highlights the Need for More Effective Wildlife Trade Legislation](https://doi.org/10.1016/j.tree.2020.10.001){target="_blank"}. **Trends in Ecology and Evolution** 35: 1052--1055 [pdf](publications/TREE_35(12)1052–1055_Boruzee&al_2020.pdf){target="_blank"}

10.1 Loveridge, R, **Ryan, GE**, Sum P, Gray-Read, O, Mahood, SP, Mould, A, Harrison, S, Crouthers, R, Ko, S., Clements, T, Eames, JC, & Pruvot, M. (2018). [Poisoning causing the decline in South-East Asia's largest vulture population — CORRIGENDUM](https://doi.org/10.1017/S0959270920000337){target="_blank"}. **Bird Conservation International** 30(3): 494

13. Brownell RL Jr, Reeves RR, Read AJ, Smith BD, Thomas PO, Ralls K, Amano M, Berggren P, Chit AM, Collins T, Currey R, Dolar L, Genov T, Hobbs R, Kreb D, Marsh H, Zhigang M, Perrin WF, Phay S, Rojas-Bracho L, **Ryan GE**, Shelden KEW, Slooten E, Taylor BL, Vidal O, Ding W, Whitty TS, & Wang JY (2019). [Bycatch in gillnet fisheries threatens Critically Endangered small cetaceans and other aquatic megafauna](https://doi.org/10.3354/esr00994){target="_blank"}. **Endangered Species Research** 40: 285--296

12. Thomas, PO, Gulland, FMD, Reeves, RR, Kreb, D, Ding, W, Smith, B, Malik, MI, **Ryan, GE**, & Phay, S (2019). [A review of electrofishing as a potential threat to freshwater cetaceans](https://doi.org/10.3354/esr00962){target="_blank"}. **Endangered Species Research** 39: 207--220

11. **Ryan, GE**, Nicholson, E, Eames, JC, Gray, TNE, Loveridge, R, Mahood, SP, Sum P, & McCarthy, MA (2019). [Simultaneous‐count models to estimate abundance from counts of unmarked individuals with imperfect detection](https://doi.org/10.1111/cobi.13261){target="_blank"}. **Conservation Biology** 33(3): 697--708

6.1. **Ryan, GE**, & Baker, CM (2019). [Corrigendum to "A general method for assessing the risks and benefits of secrecy in conserving 'Lazarus species" \[Biol. Cons. 203, 186--187\]](https://doi.org/10.1016/j.biocon.2018.12.003){target="_blank"}. **Biological Conservation** 230: 47

10. Loveridge, R, **Ryan, GE**, Sum P, Grey-Read, O, Mahood, SP, Mould, A, Harrison, S, Crouthers, R, Ko, S., Clements, T, Eames, JC, & Pruvot, M. (2018). [Poisoning causing the decline in South-East Asia's largest vulture population](https://doi.org/10.1017/S0959270918000126){target="_blank"}. **Bird Conservation International** 29(1): 41--54

9. Krutzen, M, Beasley I, Ackermann, CY, Lieckfeldt, D, Ludwig, A, **Ryan, GE**, Bejder, L, Parra, GJ, Wolfensberger, R, & Spencer, PBS (2018). [Demographic collapse and low genetic diversity of the Irrawaddy dolphin population inhabiting the Mekong River](https://doi.org/10.1371/journal.pone.0189200){target="_blank"}. **PLoS ONE** 13(1): e0189200

8. Brownell, RL, Reeves, RR, Thomas, PO, Smith, BD, & **Ryan, GE** (2017). [Dams threaten rare Mekong dolphins](https://doi.org/10.1126/science.aam6406){target="_blank"}. **Science** 355(6327): 805

7. Mustika, PLK, Welters, R, **Ryan, GE**, D'Lima, C, Sorongon-Yap, P, Jutapruet S, & Peter, C (2017). [A rapid assessment of wildlife tourism risk posed to cetaceans in Asia](http://dx.doi.org/10.1080/09669582.2016.1257012){target="_blank"}. **Journal of Sustainable Tourism** 25(8): 1138--115

6. **Ryan, GE**, & Baker, CM (2016). [A general method for assessing the risks and benefits of secrecy in conserving 'Lazarus species'](http://dx.doi.org/10.1016/j.biocon.2016.09.022){target="_blank"}. **Biological Conservation** 203: 186--187. See also Corrigendum, Ryan & Baker (2019)

5. Singh, R. Phan C, Prum S, Pin C, **Ryan, G**, & Wright, M (2013). [The Serengeti of Asia: current status of the Eastern Plains Landscape protected area complex, Cambodia](https://doi.org/10.2305/IUCN.CH.2013.PARKS-19-2.RS.en){target="_blank"}. **PARKS** 19(2): 23-32

4. **Ryan, GE** (2012). [Brahminy kites *Haliastur indus* fishing with Irrawaddy dolphins *Orcaella brevirostris* in the Mekong River](https://www.researchgate.net/publication/289744193_Brahminy_Kites_Haliastur_indus_fishing_with_Irrawaddy_dolphins_Orcaella_brevirostris_in_the_Mekong_River){target="_blank"}. **Forktail** 28: 161-162

3. Sok K, Claassen, AH, Wright, HL, & **Ryan, GE** (2012). [Waterbird nest protection on the Mekong River: a preliminary evaluation, with notes on the recovery and release of white-shouldered ibis Pseudibis davisoni chicks](https://www.fauna-flora.org/wp-content/uploads/2023/05/FFI_201207_Cambodian-Journal-of-Natural-History.pdf){target="_blank"}. **Cambodian Journal of Natural History** 2012(1): 29-41

2. McCarthy, MA, Garrard, GE, Moore, AL, Parris, KM, Regan, TJ, & **Ryan, GE** (2011). [The SAFE index should not be used for prioritization](https://doi.org/10.1890/11.WB.027){target="_blank"}. **Frontiers in Ecology and the Environment** 9(9): 486--487

1. **Ryan, GE**, Dove, V, Trujillo, F, & Doherty, PF (2011). [Irrawaddy dolphin demography in the Mekong River: an application of mark-resight models](https://doi.org/10.1890/ES10-00171.1){target="_blank"}. **Ecosphere** 2(5): art58

## Grey Literature

Shearer, Freya; Adeshina, Adekunle; Dawson, Peter; Golding, Nick; Hao, Tianxiao; Hyndman, Rob J; Moss, Rob; O'Jara-Wild, Mitchell; Price, David; **Ryan, Gerard**; Senior, Katharine; Tobin, Ruarai; Wood, James; and McCaw, James (2023). [Series of weekly COVID-19 epidemic situational assessment reports submitted to the Australian Government Department of Health Office of Health Protection from April 2020 to December 2023](https://doi.org/10.26188/24845328){target="_blank"}. https://doi.org/10.26188/24845328

McCaw, JM, R Moss, DJ Price, FM Shearer, R Tobin, N Golding, T Hao, **G Ryan**, A Adekunle, P Dawson, M Teo, D Morris, JV Ross, T South, R Hyndman, M Lydeamore, M O'Hara-Wild, and J Wood (2022). [Situational assessment of COVID-19 in Australia Technical Report 22 May 2022 (released 12 August 2022)](https://mspgh.unimelb.edu.au/__data/assets/pdf_file/0003/4256103/2022-05-22-Technical-report-public-release.pdf){target="_blank"}.

[Doherty Modelling – Final Report to National Cabinet](https://www.doherty.edu.au/uploads/content_doc/%20Synthesis_DohertyModelling_FinalReport__NatCab05Nov.pdf){target="_blank"}. 5th November 2021. (2021).

Nick Golding, Freya M. Shearer, Robert Moss, Peter Dawson, Dennis Liu, Joshua V. Ross, Rob Hyndman, Pablo Montero-Manso, **Gerry Ryan**, Tobin South, Jodie McVernon, David J. Price, and James M. McCaw, (2021). [Situational assessment of COVID-19 in Australia Technical Report 15 March 2021 (released 28 May 2021)](https://mspgh.unimelb.edu.au/__data/assets/pdf_file/0004/4230643/2021-03-15-Technical-report-public-release.pdf){target="_blank"}.

**Ryan, GE** (2021). [Birds in the sky, fish in the sea, money in the bank: quantitative methods for more effective conservation](http://hdl.handle.net/11343/274714){target="_blank"}. Thesis submitted in total fulfilment for the degree of Doctor of Philosophy, The University of Melbourne. URI: http://hdl.handle.net/11343/274714

Casey Visintin, Natalie Briscoe, Michael Kearney, **Gerry Ryan**, Craig Nitschke & Brendan Wintle (2021). [Mapping distributions, threats and opportunities to conserve the greater glider by integrating biophysical and spatially-explicit population models](https://www.nespthreatenedspecies.edu.au/media/zo3iv32y/4-4-8-greater-glider-modelling-report_v2.pdf){target="_blank"}. NESP Threatened Species Recovery Hub Project 4.4.8 report, Brisbane

Beasley, IL, & **Ryan, GE** (2017). [Assessing the impacts on Mekong River Irrawaddy dolphins from the Sambor hydropower alternatives](https://data.opendevelopmentmekong.net/en/library_record/sambor-hydropower-dam-alternatives-assessment-final-report){target="_blank"}. Chapter 9, Volume 2: Sambor Dam Alternatives, Sambor Hydropower Dam Alternatives Assessment: Final Report. Executive Summary. Technical Report.

**Ryan, GE**, Mustika PL, & Welters, R (2016). [Tourism puts dolphins at risk in Southeast Asia -- here's what to look for on your next holiday](https://theconversation.com/tourism-puts-dolphins-at-risk-in-southeast-asia-heres-what-to-look-for-on-your-next-holiday-70646){target="_blank"}. The Conversation

**Ryan, GE** (2014). [The Don Sahong Dam and the Mekong Dolphin](https://wwfint.awsassets.panda.org/downloads/donsahong_dolphin_lr_feb2014.pdf){target="_blank"}. World Wide Fund for Nature, Gland, Switzerland

Cowling, V, & **Ryan, G** (2014). Can trans-boundary management save the dolphins in Lao PDR? Catch & Culture: Fisheries Research and Development in the Mekong Region 19:2 4--5

**Ryan, GE** (2013). [Rhino horn and tiger blood: conservation in the Mekong](https://theconversation.com/rhino-horn-and-tiger-blood-conservation-in-the-mekong-11882){target="_blank"}. The Conversation

**Ryan, GE** (2013). [Is the extirpation of Irrawaddy dolphins Orcaella brevirostris in Laos imminent: an assessment of status and recommendations for conservation. SC/65a/SM05](https://archive.iwc.int/pages/view.php?ref=4704&k=){target="_blank"}. Presented to the International Whaling Commission Scientific Committee, June 2013

**Ryan, GE** (2012). [Last chance for dolphins in Laos: A review of the history, threats, and status](https://wwflac.awsassets.panda.org/downloads/last_chance_for_laos__dolphins.pdf){target="_blank"}. A Technical Report from WWF-Greater Mekong Programme, Hanoi, Vietnam

Rodgers, M, Nash, E, Blate, G, Congdon, G, & **Ryan, GE** (2012). [Resilience on the Mekong: A vulnerability and adaptation assessment in North-East Cambodia](https://wwfint.awsassets.panda.org/downloads/climate_change_report__resilience_on_the_mekong.pdf){target="_blank"}. WWF-Cambodia Technical Report, WWF-Cambodia, Phnom Penh, Cambodia

## Data

**Ryan, G**, Nicholson, E, & McCarthy, M (2024). Data and questionnaire for "The costs and benefits of publicising species discoveries". The University of Melbourne. Dataset. Figshare [DOI: 10.26188/11357126](https://doi.org/10.26188/11357126){target="_blank"}

## Archived code

**Ryan, G**, & Tierney N.. (2025). idem-lab/traveltime: zenodo release 1 (Version v4). Zenodo. [DOI: 10.5281/zenodo.15347016](https://doi.org/10.5281/zenodo.15347016){target="_blank"}

**Ryan, G**. (2024). geryan/publicising_species_discoveries. Zenodo. [DOI: 10.5281/zenodo.10622196](https://zenodo.org/doi/10.5281/zenodo.10622196){target="_blank"}

**Ryan GE**, & Golding, N. (2022). geryan/nat_plan_figs: Citable version for national plan paper (Version v1). Zenodo. [DOI: 10.5281/zenodo.7117840](https://doi.org/10.5281/zenodo.7117840){target="_blank"}

**Ryan, G.** (2018). geryan/simultaneous_count_models: Archiving release of SCM code (Version 1). Zenodo. [DOI: 10.5281/zenodo.1473876](https://doi.org/10.5281/zenodo.1473876){target="_blank"}

## Published pre-prints

*This is really for my own record; you don't want to read or cite them — see the published versions above.*

Eales, O., Teo, M., Price, D.J., Hao, T., **Ryan, G.E.**, Senior, K.L., Carlson, S., Dalton, C., Dawson, P., Golding, N., McCaw, J.M., and Shearer, F.M. (2024). [Temporal trends in test-seeking behaviour during the COVID-19 pandemic](https://doi.org/10.1101/2024.06.06.24308566){target="_blank"}. **medRxiv** 2024.06.06.24308566 *Now Eales et al. 2025 Mathematics in Medical and Life Sciences*

**Ryan, G.E.**, Tierney, N., Golding, N., and Weiss, D.J (2025). [traveltime: an R package to calculate travel time across a landscape from user-specified locations](https://doi.org/10.12688/verixiv.989.1){target="_blank"}. **VeriXiv** 2:99 DOI 10.12688/verixiv.989.1 *Now Ryan et al. 2025 Gates Open Research 9: 50*

**Ryan, G.E.**, Tierney, N., Golding, N., and Weiss, D.J (2025). [traveltime: an R package to calculate travel time across a landscape from user-specified locations](https://doi.org/10.31223/X56M74){target="_blank"}. **EarthArXiv** 10.31223/X56M74 *Updated version on VeriXiv above; now Ryan et al. 2025 Gates Open Research 9: 50*

Hao, T., **Ryan, G.E.**, Lydeamore, M., Cromer, D., Wood, J, McVernon, J, McCaw, J, Shearer, F.M., and Golding N. (2024). [Predicting immune protection against outcomes of infectious disease from population-level effectiveness data with application to COVID-19](https://doi.org/10.1101/2024.10.17.24314397){target="_blank"}. **medRxiv** 2024.10.17.24314397 *Now Hao et al. 2025 Vaccine 55: 126987*

**Ryan, G.E.**, Nicholson, E., Baker, C.M., and McCarthy, M. A. (2024). [The costs and benefits of publicising species discoveries](https://doi.org/10.32942/X2Q02W){target="_blank"}. **EcoEvoRxiv** 10.32942/X2Q02W *Now Ryan et al. 2024 Conservation Letters: 17(5): e13044*

Shearer, F.M., McCaw, J.M., **Ryan, G.E.**, Hao, T., Tierney, N., Lydeamore, M., Ellis, S., Ward, K., Wood, J., McVernon, J. and Golding, N., (2023). [Estimating the impact of test-trace-isolate-quarantine systems on SARS-CoV-2 transmission in Australia](https://doi.org/10.1101/2023.01.10.23284209){target="_blank"}. **medRxiv** 2023.01.10.23284209 *Now Shearer et al. 2024 Epidemics 47(2024): 100764*

**Ryan, G.E.**, Shearer, F.M., McCaw, J.M., McVernon, J. and Golding, N., (2022). [Estimating measures to reduce the transmission of SARS-CoV-2 in Australia to guide a ‘National Plan’ to reopening](https://doi.org/10.1101/2022.12.15.22282869){target="_blank"}. **medRxiv** 12.15.22282869 *Now Ryan et al. 2024 Epidemics 47(2024): 100763*

Conway, E., Walker, C.R., Baker, C., Lydeamore, M.J., **Ryan, G.E.**, Campbell, T., Miller, J.C., Yeung, M., Kabashima, G., Wood, J., Rebuli, N., McCaw, J.M., McVernon, J., Golding, N., Price, D.J, & Shearer, F.M. (2022). [COVID-19 vaccine coverage targets to inform reopening plans in a low incidence setting](https://doi.org/10.1101/2022.12.04.22282996){target="_blank"}. **medRxiv** 2022.12.04.22282996 *Now Conway et al.2024 Proc. Roy. Soc. B. 290(2005): 20231437*

Golding, N., Price, D.J., **Ryan, G.**, McVernon, J., McCaw, J.M. and Shearer, F.M. (2021). [Estimating the transmissibility of SARS-CoV-2 during periods of high, low and zero case incidence](https://doi.org/10.1101/2021.11.28.21264509){target="_blank"}. **medRxiv** 2021.11.28.21264509 *Now Golding et al. 2023 eLife 12:e78089*
